### ISSUE TITLE
about how to train and test

### ISSUE THREAD

**Issue by tongchangD** [SteveTsui/IDa-Det#1]
hello

Thanks for your contributions

I have some questions about how to train or test your code on coco datasets,

Have you considered creating a training or testing instruction document.

with best wishes

**Comment by tongchangD** [comment]
when i run `script.sh`
it's attention `ModuleNotFoundError: No module named 'mmdet.backbones'`

**Comment by tongchangD** [comment]
i set `cfg.data.samples_per_gpu=1 ` and  `cfg.data.workers_per_gpu=1`, bat code con't  runing in 8G memory .

**Comment by yuhua666** [comment]
Hi, I think it's because of the version problem of mmdet, but I haven't solved it yet. Have you found the appropriate version?

**Comment by tongchangD** [comment]
> Hi, I think it's because of the version problem of mmdet, but I haven't solved it yet. Have you found the appropriate version?

跑通了

**Comment by yuhua666** [comment]
请问您是怎么解决的，我运行python setup.py devlop，报错Unable to get git version

**Comment by yuhua666** [comment]
运行python setup.py
有以下报错：
Traceback (most recent call last):
  File "setup.py", line 53, in get_hash
    from mmdet.version import __version__
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'mmdet.backbones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 195, in <module>
    write_version_py()
  File "setup.py", line 71, in write_version_py
    sha = get_hash()
  File "setup.py", line 56, in get_hash
    raise ImportError('Unable to get git version')
ImportError: Unable to get git version

**Comment by shengtao-cmd** [comment]
> > Hi, I think it's because of the version problem of mmdet, but I haven't solved it yet. Have you found the appropriate version?
> 
> 跑通了
你好我想咨询一下您是怎么跑的，我一直出现一个错误ModuleNotFoundError: No module named 'mmcv._ext'
但是我看了网上的解决方法试了一下都不行，想请教您一下是否有遇到这个问题，然后是怎么解决的

**Comment by yuhua666** [comment]
你要在mmcv下面pip install



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月06日 21:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SteveTsui/IDa-Det] about how to train and test (Issue #1) |

Hi, I think it's because of the version problem of mmdet, but I haven't solved it yet. Have you found the appropriate version?

跑通了
你好我想咨询一下您是怎么跑的，我一直出现一个错误ModuleNotFoundError: No module named 'mmcv._ext'
但是我看了网上的解决方法试了一下都不行，想请教您一下是否有遇到这个问题，然后是怎么解决的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

shengtao-cmd left a comment (SteveTsui/IDa-Det#1)

Hi, I think it's because of the version problem of mmdet, but I haven't solved it yet. Have you found the appropriate version?

跑通了
你好我想咨询一下您是怎么跑的，我一直出现一个错误ModuleNotFoundError: No module named 'mmcv._ext'
但是我看了网上的解决方法试了一下都不行，想请教您一下是否有遇到这个问题，然后是怎么解决的

**Comment by shengtao-cmd** [comment]
> 你要在mmcv下面pip install
> […](#)
就是把在mmcv-0.5.1和mmdet这两个文件夹的东西安装下来是吗

**Comment by yuhua666** [comment]
是的 不能自动安装



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月06日 23:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SteveTsui/IDa-Det] about how to train and test (Issue #1) |

你要在mmcv下面pip install
…
就是把在mmcv-0.5.1和mmdet这两个文件夹的东西安装下来是吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

shengtao-cmd left a comment (SteveTsui/IDa-Det#1)

你要在mmcv下面pip install
…
就是把在mmcv-0.5.1和mmdet这两个文件夹的东西安装下来是吗

**Comment by shengtao-cmd** [comment]
> 是的 不能自动安装
> […](#)

非常感谢，我去尝试一下

**Comment by shengtao-cmd** [comment]
> 是的 不能自动安装
> […](#)

你好mmdet的问题该如何解决我看文件里面并没有setup.py

**Comment by shengtao-cmd** [comment]
> 是的 不能自动安装
> […](#)

ModuleNotFoundError: No module named 'mmdet.backbones'
您好，我也出现了这个错误，想请问您是如何解决的
