### ISSUE TITLE
AttributeError: module 'mmdet.models.dense_heads' has no attribute 'RPNHead_React_v2'

### ISSUE THREAD

**Issue by yuhua666** [SteveTsui/IDa-Det#4]
如题，dense_heads的定义中没有找到v2，是漏传了.py文件吗？

**Comment by SteveTsui** [comment]
您好，我修改了init文件，v2跟v3做了结构微调，现在project里面的RPNHead_React是最优效果的结构

**Comment by SteveTsui** [comment]
将init文件中的v2跟v3删除即可

**Comment by yuhua666** [comment]
非常感谢，目前看上去应该是可以运行了。
我想请教一下，大多数二值化网络使用Adam优化器，且有论文提出Adam优化器优于SGD。
但我注意到您的代码中的config文件使用了SGD优化器，是实验证明这样做更优吗？期待您的指导。

**Comment by yuhua666** [comment]
能请教一下如何开启训练吗？……
我运行指令：python tools/train.py --config configs/baselines/aitod_faster_rcnn_bir18.py
报错：
Model have 33.320436 paramerters.
Model has 11.199104 backbone.
Model has 4.57728 neck.
Model has 13.999205 bbox head.
loading annotations into memory...
Done (t=2.38s)
creating index...
index created!
2023-02-11 21:35:36,677 - mmdet - INFO - Start running, host: micro@user-Name, work_dir: /home/micro/users/zjl/IDa-Det-main/work_dirs/aitod_faster_rcnn_bir18
2023-02-11 21:35:36,677 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 176, in <module>
    main()
  File "tools/train.py", line 165, in main
    train_detector(
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/apis/train.py", line 476, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner.py", line 281, in train
    outputs = self.batch_processor(
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/apis/train.py", line 79, in batch_processor
    losses = model(**data)
  File "/home/micro/anaconda3/envs/ida/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/micro/anaconda3/envs/ida/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/micro/anaconda3/envs/ida/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/models/detectors/base.py", line 148, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/models/detectors/two_stage_kd.py", line 185, in forward_train
    if 'mask-neck-one' in kd_cfg.type:
AttributeError: 'NoneType' object has no attribute 'type'
