### ISSUE TITLE
关于教师模型的预训练权重

### ISSUE THREAD

**Issue by yuhua666** [SteveTsui/IDa-Det#7]
由于没有提供教师模型的预训练权重，我根据您给的代码自己训了一个。但蒸馏时出现以下报错，是我哪里出错了吗？

2023-02-12 12:01:28,423 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
kd_decay rate:  1.0
/home/micro/users/zjl/IDa-Det-main/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:159: UserWarning: This overload of addcmul is deprecated:
        addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
        addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  gx = torch.addcmul(px, 1, pw, dx)  # gx = px + pw * dx
dict_keys(['cls_score', 'bbox_pred', 'bbox_targets', 'sampling', 'neck', 'backbone', 'img_metas', 'gt_bboxes', 'gt_labels'])
Traceback (most recent call last):
  File "tools/train_entropy.py", line 206, in <module>
    main()
  File "tools/train_entropy.py", line 194, in main
    train_detector_entropy(
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/multi_distillation/detector_entropy.py", line 511, in train_detector_entropy
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, kd_cfg=cfg.model.hint_adapt)
  File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner_kd.py", line 405, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner_kd.py", line 303, in train
    outputs = self.batch_processor(
  File "/home/micro/users/zjl/IDa-Det-main/mmdet/multi_distillation/detector_entropy.py", line 211, in batch_processor_entropy
    proposal_list_s = head_det_s['proposal_list']
KeyError: 'proposal_list'

**Comment by yuhua666** [comment]
您好，代码是否存在未经核对的函数？
我修改train_entropy.py文件下的194行的train_detector_entropy改成train_detector_kd后，报错被解决了，成功运行了。
能否麻烦您核对一下这一点？因为我注意到train_detector_entropy和train_detector_kd的内容其实是一样的，但使用train_detector_entropy的时候无法training，我也感到十分迷惑。

**Comment by yuhua666** [comment]
或者，是config目录下的模型文件与蒸馏不对应？能否share一份您能正常训练时的config配置文件？

**Comment by yuhua666** [comment]
这个问题我已经解决了，是我的问题，打扰啦
